import {
  UtensilsCrossed, ShoppingBag, Plane, Globe, Users, Boxes,
} from 'lucide-react';
import type { Project, CaseStudy } from '@/types';

export const projects: Project[] = [
  {
    icon: UtensilsCrossed,
    category: 'Restaurant AI',
    title: 'AI Ordering & Demand Forecasting',
    description: 'An AI system that handles orders, predicts demand, and optimizes inventory for a multi-location restaurant chain.',
    metric: '+34%',
    metricLabel: 'revenue lift',
    accent: 'from-primary to-accent',
  },
  {
    icon: ShoppingBag,
    category: 'Ecommerce Platform',
    title: 'Headless Storefront with AI Search',
    description: 'A conversion-optimized ecommerce platform with AI-powered personalization, merchandising, and instant search.',
    metric: '+38%',
    metricLabel: 'conversion lift',
    accent: 'from-accent to-chart-3',
  },
  {
    icon: Plane,
    category: 'Travel System',
    title: 'AI Travel Planning Platform',
    description: 'An intelligent travel booking system that builds personalized itineraries and automates customer support end-to-end.',
    metric: '4.1x',
    metricLabel: 'faster booking',
    accent: 'from-chart-3 to-chart-4',
  },
  {
    icon: Globe,
    category: 'Business Website',
    title: 'Corporate Website with AI Chat',
    description: 'A premium corporate website with an integrated AI assistant that answers visitor questions and captures leads 24/7.',
    metric: '+52%',
    metricLabel: 'lead capture',
    accent: 'from-chart-4 to-primary',
  },
  {
    icon: Users,
    category: 'CRM',
    title: 'AI-Powered CRM Platform',
    description: 'A custom CRM with AI lead scoring, automated follow-ups, and predictive pipeline analytics for a sales team.',
    metric: '2.3x',
    metricLabel: 'pipeline growth',
    accent: 'from-primary to-chart-5',
  },
  {
    icon: Boxes,
    category: 'ERP',
    title: 'Enterprise Resource Planning System',
    description: 'A unified ERP platform integrating inventory, finance, and operations with AI-driven forecasting and anomaly detection.',
    metric: '41%',
    metricLabel: 'cost reduction',
    accent: 'from-chart-5 to-accent',
  },
];

export const caseStudies: CaseStudy[] = [
  {
    icon: UtensilsCrossed,
    category: 'Restaurant AI',
    title: 'AI Ordering & Demand Forecasting',
    overview: 'A multi-location restaurant chain needed to reduce wait times and optimize inventory across 40+ locations.',
    challenge: 'Manual ordering and inventory management led to stockouts, food waste, and inconsistent customer experiences across locations.',
    solution: 'We built an AI system that handles voice and digital orders, predicts demand based on historical data and weather, and auto-adjusts inventory orders.',
    outcome: '+34% revenue lift, 28% reduction in food waste, and order accuracy improved to 99.2% across all locations.',
    tech: ['Next.js', 'Python', 'PostgreSQL', 'OpenAI', 'AWS'],
    metrics: [
      { value: '+34%', label: 'Revenue lift' },
      { value: '-28%', label: 'Food waste' },
      { value: '99.2%', label: 'Order accuracy' },
    ],
    accent: 'from-primary to-accent',
  },
  {
    icon: ShoppingBag,
    category: 'Ecommerce Platform',
    title: 'Headless Storefront with AI Search',
    overview: 'A fast-growing DTC brand needed a storefront that could scale and personalize the shopping experience.',
    challenge: 'Their legacy platform was slow, search was generic, and conversion rates were stagnating despite growing traffic.',
    solution: 'We built a headless commerce platform with AI-powered search, personalized recommendations, and a sub-second checkout flow.',
    outcome: '+38% conversion lift, 2.1x average order value, and page load times dropped from 3.4s to 0.8s.',
    tech: ['Next.js', 'TypeScript', 'Supabase', 'Stripe', 'Vercel'],
    metrics: [
      { value: '+38%', label: 'Conversion lift' },
      { value: '2.1x', label: 'AOV increase' },
      { value: '0.8s', label: 'Load time' },
    ],
    accent: 'from-accent to-chart-3',
  },
  {
    icon: Plane,
    category: 'Travel System',
    title: 'AI Travel Planning Platform',
    overview: 'A travel agency wanted to offer personalized itineraries at scale without growing their operations team.',
    challenge: 'Agents spent hours building custom itineraries manually, limiting how many customers they could serve.',
    solution: 'We deployed an AI travel planning system that builds personalized itineraries from natural language requests and automates bookings.',
    outcome: '4.1x faster booking, 92% customer satisfaction with AI-generated itineraries, and 3x more customers served per agent.',
    tech: ['React', 'Node.js', 'OpenAI', 'PostgreSQL', 'Redis'],
    metrics: [
      { value: '4.1x', label: 'Faster booking' },
      { value: '92%', label: 'CSAT' },
      { value: '3x', label: 'Customers/agent' },
    ],
    accent: 'from-chart-3 to-chart-4',
  },
  {
    icon: Globe,
    category: 'Business Website',
    title: 'Corporate Website with AI Chat',
    overview: 'A B2B SaaS company needed a premium website that could capture and qualify leads automatically.',
    challenge: 'Their existing site was outdated, generated few leads, and had no way to engage visitors outside business hours.',
    solution: 'We built a premium corporate website with an integrated AI assistant that answers questions, qualifies leads, and books demos 24/7.',
    outcome: '+52% lead capture, 40% of leads now qualified by AI before reaching sales, and demo bookings tripled.',
    tech: ['Next.js', 'Tailwind', 'Supabase', 'OpenAI', 'Vercel'],
    metrics: [
      { value: '+52%', label: 'Lead capture' },
      { value: '40%', label: 'AI-qualified' },
      { value: '3x', label: 'Demo bookings' },
    ],
    accent: 'from-chart-4 to-primary',
  },
  {
    icon: Users,
    category: 'CRM',
    title: 'AI-Powered CRM Platform',
    overview: 'A sales team was losing deals because their generic CRM didn\'t match their process or prioritize effectively.',
    challenge: 'Sales reps spent more time managing the CRM than selling, and leadership had no visibility into pipeline health.',
    solution: 'We built a custom CRM with AI lead scoring, automated follow-up sequences, and predictive pipeline analytics.',
    outcome: '2.3x pipeline growth, 45% reduction in admin time per rep, and forecast accuracy improved to 91%.',
    tech: ['Next.js', 'Prisma', 'PostgreSQL', 'OpenAI', 'AWS'],
    metrics: [
      { value: '2.3x', label: 'Pipeline growth' },
      { value: '-45%', label: 'Admin time' },
      { value: '91%', label: 'Forecast accuracy' },
    ],
    accent: 'from-primary to-chart-5',
  },
  {
    icon: Boxes,
    category: 'ERP',
    title: 'Enterprise Resource Planning System',
    overview: 'A manufacturing company needed to unify inventory, finance, and operations across multiple facilities.',
    challenge: 'Data was scattered across spreadsheets and legacy systems, creating blind spots and costly errors.',
    solution: 'We built a unified ERP platform integrating inventory, finance, and operations with AI-driven forecasting and anomaly detection.',
    outcome: '41% cost reduction, real-time visibility across all facilities, and anomaly detection caught $340k in billing errors.',
    tech: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'AWS'],
    metrics: [
      { value: '41%', label: 'Cost reduction' },
      { value: '$340k', label: 'Errors caught' },
      { value: '100%', label: 'Real-time' },
    ],
    accent: 'from-chart-5 to-accent',
  },
];
